# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pi_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import serial.tools.list_ports
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
import time
from pyvesc import VESC
import math

# Global variables for thread-safe communication
vesc_com_flag = threading.Event()
prog_flag = threading.Event()
reset_flag = threading.Event()
freewheel = threading.Event()
freewheel.set()

vesc_values = {}  # Dictionary to store all VESC values
selected_port = None  # To store the selected COM port
control_value = 0.0  # Global variable for control value
control_mode = "Current"  # Default control mode
bicycle_mode = "dyn"
speed = 0 #vehicle speed
dist = 0 #traveled distance
elev = 0 #elevation distance
is_free = 1 # is freewheeling

# Motor params, could read from config but doing manually by now

L_mot = 76.1e-6
L_mot_del = 44.57e-6
fluxl = 6.361e-3
polepairs = 7

# Mechanical properties: dependend on mechanical setup: mech_gear/gears

#mech_gear = 17.78
mech_gear = 25
gears = [0.7500, 1.1250, 1.5000, 1.8750, 2.2500, 2.6250, 3.0000, 3.3750, 3.7500, 4.1250, 4.5000]
wheel_diam = 28

# properties for bicycle dynamics

mu_rr = 0.005
air_ro = 1.2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 440)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Mode = QtWidgets.QGroupBox(self.centralwidget)
        self.Mode.setGeometry(QtCore.QRect(60, 200, 141, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Mode.setFont(font)
        self.Mode.setObjectName("Mode")
        self.Button_dyn = QtWidgets.QRadioButton(self.Mode)
        self.Button_dyn.setGeometry(QtCore.QRect(15, 30, 110, 23))
        self.Button_dyn.setChecked(True)
        self.Button_dyn.setObjectName("Button_dyn")
        self.Button_spin = QtWidgets.QRadioButton(self.Mode)
        self.Button_spin.setGeometry(QtCore.QRect(15, 60, 110, 23))
        self.Button_spin.setObjectName("Button_spin")
        self.Button_Ergometer = QtWidgets.QRadioButton(self.Mode)
        self.Button_Ergometer.setGeometry(QtCore.QRect(15, 90, 110, 23))
        self.Button_Ergometer.setObjectName("Button_Ergometer")
        self.gearselector = QtWidgets.QSpinBox(self.centralwidget)
        self.gearselector.setGeometry(QtCore.QRect(400, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gearselector.setFont(font)
        self.gearselector.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.gearselector.setSpecialValueText("")
        self.gearselector.setMinimum(1)
        self.gearselector.setMaximum(11)
        self.gearselector.setObjectName("gearselector")
        self.Slider_incline = QtWidgets.QSlider(self.centralwidget)
        self.Slider_incline.setEnabled(True)
        self.Slider_incline.setGeometry(QtCore.QRect(400, 20, 231, 51))
        self.Slider_incline.setMinimum(-45)
        self.Slider_incline.setMaximum(45)
        self.Slider_incline.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_incline.setInvertedControls(False)
        self.Slider_incline.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_incline.setTickInterval(5)
        self.Slider_incline.setObjectName("Slider_incline")
        self.label_incline = QtWidgets.QLabel(self.centralwidget)
        self.label_incline.setGeometry(QtCore.QRect(280, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_incline.setFont(font)
        self.label_incline.setObjectName("label_incline")
        self.label_gear = QtWidgets.QLabel(self.centralwidget)
        self.label_gear.setGeometry(QtCore.QRect(320, 140, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_gear.setFont(font)
        self.label_gear.setObjectName("label_gear")
        self.Slider_airspeed = QtWidgets.QSlider(self.centralwidget)
        self.Slider_airspeed.setGeometry(QtCore.QRect(400, 80, 231, 51))
        self.Slider_airspeed.setMinimum(-30)
        self.Slider_airspeed.setMaximum(30)
        self.Slider_airspeed.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_airspeed.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_airspeed.setTickInterval(5)
        self.Slider_airspeed.setObjectName("Slider_airspeed")
        self.label_airspeed = QtWidgets.QLabel(self.centralwidget)
        self.label_airspeed.setGeometry(QtCore.QRect(220, 80, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_airspeed.setFont(font)
        self.label_airspeed.setObjectName("label_airspeed")
        self.line_incline = QtWidgets.QLineEdit(self.centralwidget)
        self.line_incline.setGeometry(QtCore.QRect(650, 10, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_incline.setFont(font)
        self.line_incline.setTabletTracking(False)
        self.line_incline.setAlignment(QtCore.Qt.AlignCenter)
        self.line_incline.setObjectName("line_incline")
        self.line_airspeed = QtWidgets.QLineEdit(self.centralwidget)
        self.line_airspeed.setGeometry(QtCore.QRect(650, 70, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_airspeed.setFont(font)
        self.line_airspeed.setAlignment(QtCore.Qt.AlignCenter)
        self.line_airspeed.setObjectName("line_airspeed")
        self.startstop = QtWidgets.QFrame(self.centralwidget)
        self.startstop.setGeometry(QtCore.QRect(30, 130, 251, 51))
        self.startstop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startstop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.startstop.setObjectName("startstop")
        self.start = QtWidgets.QPushButton(self.startstop)
        self.start.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.startstop)
        self.stop.setGeometry(QtCore.QRect(90, 10, 71, 31))
        self.stop.setObjectName("stop")
        self.Reset = QtWidgets.QPushButton(self.startstop)
        self.Reset.setGeometry(QtCore.QRect(170, 10, 71, 31))
        self.Reset.setObjectName("Reset")
        self.mass = QtWidgets.QFrame(self.centralwidget)
        self.mass.setGeometry(QtCore.QRect(250, 200, 171, 71))
        self.mass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mass.setObjectName("mass")
        self.line_bikemass = QtWidgets.QLineEdit(self.mass)
        self.line_bikemass.setGeometry(QtCore.QRect(120, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_bikemass.setFont(font)
        self.line_bikemass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_bikemass.setObjectName("line_bikemass")
        self.line_drivermass = QtWidgets.QLineEdit(self.mass)
        self.line_drivermass.setGeometry(QtCore.QRect(120, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_drivermass.setFont(font)
        self.line_drivermass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_drivermass.setObjectName("line_drivermass")
        self.label_bikemass = QtWidgets.QLabel(self.mass)
        self.label_bikemass.setGeometry(QtCore.QRect(0, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_bikemass.setFont(font)
        self.label_bikemass.setObjectName("label_bikemass")
        self.label_drivermass = QtWidgets.QLabel(self.mass)
        self.label_drivermass.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_drivermass.setFont(font)
        self.label_drivermass.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_drivermass.setObjectName("label_drivermass")
        self.energy = QtWidgets.QFrame(self.centralwidget)
        self.energy.setGeometry(QtCore.QRect(540, 220, 221, 191))
        self.energy.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.energy.setFrameShadow(QtWidgets.QFrame.Raised)
        self.energy.setObjectName("energy")
        self.line_speed = QtWidgets.QLineEdit(self.energy)
        self.line_speed.setGeometry(QtCore.QRect(170, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_speed.setFont(font)
        self.line_speed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_speed.setReadOnly(True)
        self.line_speed.setObjectName("line_speed")
        self.line_pot_energy = QtWidgets.QLineEdit(self.energy)
        self.line_pot_energy.setGeometry(QtCore.QRect(170, 40, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_pot_energy.setFont(font)
        self.line_pot_energy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_pot_energy.setReadOnly(True)
        self.line_pot_energy.setObjectName("line_pot_energy")
        self.label_pot_energy = QtWidgets.QLabel(self.energy)
        self.label_pot_energy.setGeometry(QtCore.QRect(0, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_pot_energy.setFont(font)
        self.label_pot_energy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pot_energy.setObjectName("label_pot_energy")
        self.label_elevation = QtWidgets.QLabel(self.energy)
        self.label_elevation.setGeometry(QtCore.QRect(0, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_elevation.setFont(font)
        self.label_elevation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_elevation.setObjectName("label_elevation")
        self.line_elevation = QtWidgets.QLineEdit(self.energy)
        self.line_elevation.setGeometry(QtCore.QRect(170, 0, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_elevation.setFont(font)
        self.line_elevation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_elevation.setReadOnly(True)
        self.line_elevation.setObjectName("line_elevation")
        self.label_speed = QtWidgets.QLabel(self.energy)
        self.label_speed.setGeometry(QtCore.QRect(0, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_speed.setFont(font)
        self.label_speed.setObjectName("label_speed")
        self.label_kin_energy = QtWidgets.QLabel(self.energy)
        self.label_kin_energy.setGeometry(QtCore.QRect(0, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_kin_energy.setFont(font)
        self.label_kin_energy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_kin_energy.setObjectName("label_kin_energy")
        self.line_kin_energy = QtWidgets.QLineEdit(self.energy)
        self.line_kin_energy.setGeometry(QtCore.QRect(170, 120, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_kin_energy.setFont(font)
        self.line_kin_energy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_kin_energy.setReadOnly(True)
        self.line_kin_energy.setObjectName("line_kin_energy")
        self.label_distance = QtWidgets.QLabel(self.energy)
        self.label_distance.setGeometry(QtCore.QRect(0, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_distance.setFont(font)
        self.label_distance.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_distance.setObjectName("label_distance")
        self.line_distance = QtWidgets.QLineEdit(self.energy)
        self.line_distance.setGeometry(QtCore.QRect(170, 160, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_distance.setFont(font)
        self.line_distance.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.line_distance.setReadOnly(True)
        self.line_distance.setObjectName("line_distance")
        self.rpm = QtWidgets.QFrame(self.centralwidget)
        self.rpm.setGeometry(QtCore.QRect(250, 290, 171, 111))
        self.rpm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rpm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rpm.setObjectName("rpm")
        self.line_pedrpm = QtWidgets.QLineEdit(self.rpm)
        self.line_pedrpm.setGeometry(QtCore.QRect(100, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_pedrpm.setFont(font)
        self.line_pedrpm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_pedrpm.setReadOnly(True)
        self.line_pedrpm.setObjectName("line_pedrpm")
        self.line_sysrpm = QtWidgets.QLineEdit(self.rpm)
        self.line_sysrpm.setGeometry(QtCore.QRect(100, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_sysrpm.setFont(font)
        self.line_sysrpm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_sysrpm.setReadOnly(True)
        self.line_sysrpm.setObjectName("line_sysrpm")
        self.label_pedrpm = QtWidgets.QLabel(self.rpm)
        self.label_pedrpm.setGeometry(QtCore.QRect(0, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_pedrpm.setFont(font)
        self.label_pedrpm.setObjectName("label_pedrpm")
        self.label_sysrpm = QtWidgets.QLabel(self.rpm)
        self.label_sysrpm.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_sysrpm.setFont(font)
        self.label_sysrpm.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_sysrpm.setObjectName("label_sysrpm")
        self.label_power = QtWidgets.QLabel(self.rpm)
        self.label_power.setGeometry(QtCore.QRect(0, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_power.setFont(font)
        self.label_power.setObjectName("label_power")
        self.line_power = QtWidgets.QLineEdit(self.rpm)
        self.line_power.setGeometry(QtCore.QRect(100, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_power.setFont(font)
        self.line_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.line_power.setReadOnly(True)
        self.line_power.setObjectName("line_power")
        self.pushButton_upshift = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_upshift.setGeometry(QtCore.QRect(490, 140, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_upshift.setFont(font)
        self.pushButton_upshift.setObjectName("pushButton_upshift")
        self.pushButton_downshift = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_downshift.setGeometry(QtCore.QRect(560, 140, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_downshift.setFont(font)
        self.pushButton_downshift.setObjectName("pushButton_downshift")
        self.pushButton_incline_res = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_incline_res.setGeometry(QtCore.QRect(730, 10, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_incline_res.setFont(font)
        self.pushButton_incline_res.setObjectName("pushButton_incline_res")
        self.pushButton_airspeed_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_airspeed_reset.setGeometry(QtCore.QRect(730, 70, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_airspeed_reset.setFont(font)
        self.pushButton_airspeed_reset.setObjectName("pushButton_airspeed_reset")
        self.comboBox_portselect = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_portselect.setGeometry(QtCore.QRect(10, 10, 101, 22))
        self.comboBox_portselect.setObjectName("comboBox_portselect")
        self.refresh_ports()
        self.pushButton_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_refresh.setGeometry(QtCore.QRect(120, 10, 61, 23))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(100, 50, 81, 41))
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(10, 50, 81, 41))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.radioButton_freewheel = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_freewheel.setGeometry(QtCore.QRect(70, 370, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_freewheel.setFont(font)
        self.radioButton_freewheel.setChecked(True)
        self.radioButton_freewheel.setObjectName("radioButton_freewheel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Button_spin, self.Button_Ergometer)
        MainWindow.setTabOrder(self.Button_Ergometer, self.gearselector)
        MainWindow.setTabOrder(self.gearselector, self.Slider_incline)
        MainWindow.setTabOrder(self.Slider_incline, self.line_incline)
        MainWindow.setTabOrder(self.line_incline, self.Slider_airspeed)
        MainWindow.setTabOrder(self.Slider_airspeed, self.Button_dyn)
        MainWindow.setTabOrder(self.Button_dyn, self.line_airspeed)
        MainWindow.setTabOrder(self.line_airspeed, self.start)
        MainWindow.setTabOrder(self.start, self.stop)
        MainWindow.setTabOrder(self.stop, self.Reset)
        MainWindow.setTabOrder(self.Reset, self.line_elevation)
        MainWindow.setTabOrder(self.line_elevation, self.line_bikemass)
        MainWindow.setTabOrder(self.line_bikemass, self.line_drivermass)
        MainWindow.setTabOrder(self.line_drivermass, self.line_pot_energy)
        MainWindow.setTabOrder(self.line_pot_energy, self.line_kin_energy)
        MainWindow.setTabOrder(self.line_kin_energy, self.line_speed)
        MainWindow.setTabOrder(self.line_speed, self.line_pedrpm)
        MainWindow.setTabOrder(self.line_pedrpm, self.line_sysrpm)

        # Connections
        self.Slider_incline.valueChanged.connect(self.updateIncline)
        self.line_incline.textChanged.connect(self.validateIncline)
        self.pushButton_incline_res.clicked.connect(self.resetIncline)

        self.Slider_airspeed.valueChanged.connect(self.updateAirspeed)
        self.line_airspeed.textChanged.connect(self.validateAirspeed)
        self.pushButton_airspeed_reset.clicked.connect(self.resetAirspeed)

        self.pushButton_upshift.clicked.connect(self.incrementGear)
        self.pushButton_downshift.clicked.connect(self.decrementGear)

        self.pushButton_refresh.clicked.connect(self.refresh_ports)

        self.Button_dyn.clicked.connect(self.set_dyn)
        self.Button_spin.clicked.connect(self.set_spin)
        self.Button_Ergometer.clicked.connect(self.set_erg)


        # Connect Button
        self.pushButton_connect.clicked.connect(self.start_com)

        # Disconnect Button
        self.pushButton_disconnect.clicked.connect(self.stop_com)

        # Start Button
        self.start.clicked.connect(self.start_prog)

        # Stop Button
        self.stop.clicked.connect(self.stop_prog)

        # Reset Button
        self.Reset.clicked.connect(self.reset_prog)

        self.radioButton_freewheel.clicked.connect(self.set_freewheel)


        MainWindow.setCentralWidget(self.centralwidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Mode.setTitle(_translate("MainWindow", "Mode"))
        self.Button_dyn.setText(_translate("MainWindow", "Dynamics"))
        self.Button_spin.setText(_translate("MainWindow", "Spinning"))
        self.Button_Ergometer.setText(_translate("MainWindow", "Ergometer"))
        self.label_incline.setText(_translate("MainWindow", "Steigung"))
        self.label_gear.setText(_translate("MainWindow", "Gang"))
        self.label_airspeed.setText(_translate("MainWindow", "Windgeschw."))
        self.line_incline.setText(_translate("MainWindow", "0"))
        self.line_airspeed.setText(_translate("MainWindow", "0"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.stop.setText(_translate("MainWindow", "Stop"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.line_bikemass.setText(_translate("MainWindow", "10"))
        self.line_drivermass.setText(_translate("MainWindow", "85"))
        self.label_bikemass.setText(_translate("MainWindow", "Bike Mass:"))
        self.label_drivermass.setText(_translate("MainWindow", "Driver Mass:"))
        self.line_speed.setText(_translate("MainWindow", "0"))
        self.line_pot_energy.setText(_translate("MainWindow", "0"))
        self.label_pot_energy.setText(_translate("MainWindow", "Potential Energy:"))
        self.label_elevation.setText(_translate("MainWindow", "Elevation:"))
        self.line_elevation.setText(_translate("MainWindow", "0"))
        self.label_speed.setText(_translate("MainWindow", "Speed:"))
        self.label_kin_energy.setText(_translate("MainWindow", "Kinetic Energy:"))
        self.line_kin_energy.setText(_translate("MainWindow", "0"))
        self.label_distance.setText(_translate("MainWindow", "Distance:"))
        self.line_distance.setText(_translate("MainWindow", "0"))
        self.line_pedrpm.setText(_translate("MainWindow", "0"))
        self.line_sysrpm.setText(_translate("MainWindow", "0"))
        self.label_pedrpm.setText(_translate("MainWindow", "Ped RPM:"))
        self.label_sysrpm.setText(_translate("MainWindow", "Sys RPM:"))
        self.label_power.setText(_translate("MainWindow", "Power:"))
        self.line_power.setText(_translate("MainWindow", "0"))
        self.pushButton_upshift.setText(_translate("MainWindow", "+"))
        self.pushButton_downshift.setText(_translate("MainWindow", "-"))
        self.pushButton_incline_res.setText(_translate("MainWindow", "0"))
        self.pushButton_airspeed_reset.setText(_translate("MainWindow", "0"))
        self.pushButton_refresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
        self.radioButton_freewheel.setText(_translate("MainWindow", "Freilauf"))

    # Methods for interactivity
    def set_dyn(self):
        global bicycle_mode
        bicycle_mode = "dyn"

    def set_spin(self):
        global bicycle_mode
        bicycle_mode = "spin"

    def set_erg(self):
        global bicycle_mode
        bicycle_mode = "erg"

    def incrementGear(self):
        if self.gearselector.value() < self.gearselector.maximum():
            self.gearselector.setValue(self.gearselector.value() + 1)

    def decrementGear(self):
        if self.gearselector.value() > self.gearselector.minimum():
            self.gearselector.setValue(self.gearselector.value() - 1)

    def updateIncline(self, value):
        self.line_incline.setText(str(value))

    def validateIncline(self):
        try:
            value = int(self.line_incline.text())
            if value < self.Slider_incline.minimum() or value > self.Slider_incline.maximum():
                print("Warning: Incline value out of range!")
        except ValueError:
            pass

    def resetIncline(self):
        self.Slider_incline.setValue(0)
        self.line_incline.setText("0")

    def updateAirspeed(self, value):
        self.line_airspeed.setText(str(value))

    def validateAirspeed(self):
        try:
            value = int(self.line_airspeed.text())
            if value < self.Slider_airspeed.minimum() or value > self.Slider_airspeed.maximum():
                print("Warning: Airspeed value out of range!")
        except ValueError:
            pass

    def start_com(self):
        """Start VESC control with the selected COM port."""
        global selected_port
        selected_port = self.comboBox_portselect.currentText()
        if selected_port:
            vesc_com_flag.set()

    def stop_com(self):
        """Stop VESC control."""
        vesc_com_flag.clear()

    def resetAirspeed(self):
        self.Slider_airspeed.setValue(0)
        self.line_airspeed.setText("0")

    def start_prog(self):
        """Start VESC control with the selected COM port."""
        prog_flag.set()

    def stop_prog(self):
        global control_value, control_mode
        """Stop VESC control."""
        control_value = 0.0
        control_mode = "Current"
        prog_flag.clear()

    def reset_prog(self):
        global speed, control_value, control_mode, dist, elev

        if prog_flag.is_set():
            prog_flag.clear()
            speed = 0
            dist = 0
            elev = 0
            control_value = 0.0
            control_mode = "Current"

        self.Slider_incline.setValue(0)
        self.line_incline.setText("0")
        self.Slider_airspeed.setValue(0)
        self.line_airspeed.setText("0")
        self.line_speed.setText("0")
        self.line_kin_energy.setText("0")
        self.line_elevation.setText("0")
        self.line_pot_energy.setText("0")
        self.line_sysrpm.setText("0")
        self.line_pedrpm.setText("0")
        self.gearselector.setValue(1)

    def set_freewheel(self):
        global freewheel
        if self.radioButton_freewheel.isChecked():
            freewheel.set()
        elif self.radioButton_freewheel.isChecked() == 0:
            freewheel.clear()


    def refresh_ports(self):
        """Refresh the list of serial ports."""
        self.comboBox_portselect.clear()
        ports = serial.tools.list_ports.comports()
        for port in ports:
            self.comboBox_portselect.addItem(port.device)

    def select_port(self):
        """Handle the selection of a port."""
        selected_port = self.comboBox_portselect.currentText()
        if selected_port:
            self.selected_port_label.setText(f"Selected Port: {selected_port}")
        else:
            self.selected_port_label.setText("Selected Port: None")

def vesc_communication():
    """Thread function for communicating with the VESC at 100 Hz."""
    global vesc_values, selected_port, control_value, control_mode
    while True:
        if vesc_com_flag.is_set() and selected_port:
            try:
                with VESC(serial_port=selected_port) as vesc:
                    while vesc_com_flag.is_set():
                        start_time = time.perf_counter()  # Start time for loop iteration

                        # Request values from VESC
                        response = vesc.get_measurements()
                        while response == None:
                            response = vesc.get_measurements()

                        # Update vesc_values dictionary with all the values
                        vesc_values = {
                            "RPM": response.rpm,
                            "Pos": response.pid_pos_now,
                            "Motor Current": response.avg_motor_current,
                            "ID": response.avg_id,
                            "IQ": response.avg_iq,
                            "Input Voltage": response.v_in,
                            "Duty Cycle": response.duty_cycle_now,
                            "Battery Current": response.avg_input_current,
                            "Fet Temperature": response.temp_fet,
                            "Amp Hours": response.amp_hours,
                            "Watt Hours": response.watt_hours,
                            "Fault Code": response.mc_fault_code,
                            "Power": response.v_in * response.duty_cycle_now * response.avg_motor_current,
                        }

                        # Send control command based on selected control mode
                        if control_mode == "Duty Cycle":
                            vesc.set_duty_cycle(control_value)
                        elif control_mode == "Current":
                            vesc.set_current(control_value)
                        elif control_mode == "Position":
                            vesc.set_servo(control_value)
                        elif control_mode == "Speed":
                            vesc.set_rpm(int(control_value))
                        elif control_mode == []:
                            vesc.set_current(0)
                        # Calculate elapsed time and sleep to maintain 100 Hz
                        elapsed_time = time.perf_counter() - start_time
                        sleep_time = max(0, (1 / 100) - elapsed_time)
                        time.sleep(sleep_time)
            except Exception as e:
                print(f"VESC Communication Error: {e}")
                vesc_com_flag.clear()
        else:
            time.sleep(0.1)

def control_logic():
    """Thread function for control logic."""
    global vesc_values, control_value, control_mode, speed, bicycle_mode, is_free, dist, elev
    while True:
        if vesc_com_flag.is_set() and prog_flag.is_set():
            control_start_time = time.perf_counter()  # Start time for loop iteration
            control_mode = "Speed"

            Lq = L_mot - 1.5 * L_mot_del
            Ld = L_mot + 1.5 * L_mot_del

            my_torque = 1.5 * (polepairs*(vesc_values.get("IQ")*(vesc_values.get("ID")*Ld+fluxl)-vesc_values.get("ID")*vesc_values.get("IQ")*Lq))

            if bicycle_mode == "dyn":

                set_erpm = (speed * 60 * polepairs * (mech_gear/gears[ui.gearselector.value()-1])) / (math.pi * wheel_diam * 0.0254)
                my_force = -(my_torque * (mech_gear/gears[ui.gearselector.value()-1]))/(wheel_diam * 0.0254/2)

                net_airspeed = pow(abs(speed + float(ui.line_airspeed.text())/3.6),2)

                if (speed + float(ui.line_airspeed.text())/3.6) < 0:
                    net_airspeed = net_airspeed * (-1)
                    #print(speed + float(ui.line_airspeed.text())/3.6)

                F_air = - net_airspeed * air_ro * 0.25
                F_roll = - (float(ui.line_bikemass.text())+float(ui.line_drivermass.text())) * 9.81 * mu_rr
                F_incline = - (float(ui.line_bikemass.text())+float(ui.line_drivermass.text())) * 9.81 * math.sin(float(ui.line_incline.text()) * math.pi / 400)
                F_combine = F_air + F_roll + F_incline

                #print(F_air)

                accel = (F_combine + my_force) / (float(ui.line_bikemass.text())+float(ui.line_drivermass.text()))

                speed = speed + accel * 0.005
                if speed < 0:
                    speed = 0

                dist = dist + speed * 0.005
                elev = elev + speed * math.sin(float(ui.line_incline.text()) * math.pi / 400) * 0.005

                if freewheel.is_set():
                    is_free = 1
                    if vesc_values.get("RPM") < .95 * set_erpm and vesc_values.get("Motor Current") > -0.3:

                        control_mode = "Current"
                        control_value = 0.0

                    elif vesc_values.get("RPM") >= .95 * set_erpm:

                        control_mode = "Speed"
                        control_value = set_erpm

                else:
                    if is_free == 1:

                        if vesc_values.get("RPM") < .95 * set_erpm and vesc_values.get("Motor Current") > -0.3:

                            control_mode = "Current"
                            control_value = 0.0

                        elif vesc_values.get("RPM") >= .95 * set_erpm:

                            control_mode = "Speed"
                            control_value = set_erpm
                            is_free = 0

                    elif is_free == 0:

                        control_mode = "Speed"
                        control_value = set_erpm


                ui.line_speed.setText(str(int(speed*3.6)))
                ui.line_kin_energy.setText(str(int(0.0005 * (float(ui.line_bikemass.text())+float(ui.line_drivermass.text())) * pow(speed,2))))
                ui.line_elevation.setText(str(int(elev)))
                ui.line_pot_energy.setText(str(int(0.0001*elev * 9.81 * (float(ui.line_bikemass.text())+float(ui.line_drivermass.text())))))
                ui.line_distance.setText(str(int(dist)))


            #elif bicycle_mode == "spin":
                #


            #elif bicycle_mode == "erg":
                #


            ui.line_pedrpm.setText(str(int(vesc_values.get("RPM"))))
            ui.line_sysrpm.setText(str(int(set_erpm)))
            ui.line_power.setText(str(int( vesc_values.get("Motor Current") * vesc_values.get("Input Voltage") * vesc_values.get("Duty Cycle") )))

            control_elapsed_time = time.perf_counter() - control_start_time
            control_sleep_time = max(0, (1 / 200) - control_elapsed_time)
            #print(control_elapsed_time+control_sleep_time)
            time.sleep(control_sleep_time)
        else:
            time.sleep(0.5)

if __name__ == "__main__":

    communication_thread = threading.Thread(target=vesc_communication, daemon=True)
    control_logic_thread = threading.Thread(target=control_logic, daemon=True)
    communication_thread.start()
    control_logic_thread.start()

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
